[project]
name = "aioapcaccess"
description = "Async version of apcaccess library implemented in python."
version = "0.1.0"
authors = [
    { name = "Yuxin Wang", email = "yuxinwang.dev@gmail.com" }
]
dependencies = []

[project.optional-dependencies]
dev = [
    "tox",
    "pytest",
    "pytest-asyncio"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]