[project]
name = "aioapcaccess"
requires-python = ">=3.7"
description = "Async version of apcaccess library implemented in python."
version = "0.1.0"
authors = [
    { name = "Yuxin Wang", email = "yuxinwang.dev@gmail.com" }
]
dependencies = []

[project.optional-dependencies]
dev = [
    "tox",
    "pytest",
    "pytest-asyncio",
    "mypy",
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.black]
line-length = 99
target-version = ['py37']

[tool.isort]
atomic = true
profile = "black"
line_length = 99
force_sort_within_sections = true
skip_gitignore = true
combine_as_imports = true
known_first_party = ["aioapcaccess", "tests"]
forced_separate = ["tests"]

[tool.bandit]
exclude_dirs = ["tests"]
